name: AWS codecommit
on:
  push
env:
  INPUT_REPOSITORY_NAME : "github-codepipe"
  AWS_REGION : eu-central-1
  AWS_CODECOMMIT_URL: https://git-codecommit.eu-central-1.amazonaws.com/v1/repos/github-codepipe
  AWS_ASSUME_ROLE: arn:aws:iam::419653499649:role/githubconnectivity-Role-1I75IQ2NQK1XR
  AWS_ROLE_NAME: githubconnectivity-Role-1I75IQ2NQK1XR
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  awscodecommit:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.AWS_ASSUME_ROLE }}
          role-session-name: ${{ env.AWS_ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}
      # Sync to AWS codecommit

      - name:  Sync to AWS codecommit
        run: |
            #!/bin/sh
            set -ue
            git config --global credential.'https://git-codecommit.*.amazonaws.com'.helper '!aws codecommit credential-helper $@'
            git config --global --add safe.directory /github/workspace
            git config --global credential.UseHttpPath true

            git pull
            git remote set-url origin ${{ env.AWS_CODECOMMIT_URL }}

            git config pull.ff only
            git push origin main --force
            git push origin HEAD:main 
            git push origin main